.TH QUIZLIGHT 1
.SH NAME
quizlight - A simple and modular terminal-based quiz program.

.SH SYNOPSIS
.B quizlight

.SH DESCRIPTION
\fBquizlight\fP is a terminal-based quiz program. It is designed to be modular; for more information on designing quiz modules, see 'man 5 quizlight'. It comes with a python3 module, based on The Python Tutorial, which can be found at:
    
    https://docs.python.org/3/tutorial/

.SH EXAMPLES
    quizlight

.SH SEE ALSO
    quizlight(5)

.SH FILES
    /usr/share/doc/quizlight/examplemodule.py
    /usr/share/doc/quizlight/README.md
    /usr/share/doc/quizlight/LICENSE

.SH AUTHOR
    Dan Persons (dpersonsdev@gmail.com)

.SH COPYRIGHT
MIT License

Copyright (c) 2017 Dan Persons

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
